version : '3'

volumes:
  pgdata:

services:

  nginx:
    depends_on:
      - python
#    image: 'python:3.6'
    build:
      context: .
      dockerfile: "docker/nginx/dockerfile"
#    Workaround on Linux of want to forward requests to
#    a machine differen than the one hosting the container uncomment
#    and set the host.docker.internal ip to the ip of the machine 
#    request should be forwarded to.
#    Note: 3/3/2019 - Linux doesn't support host.docker.internal so 
#      also need to uncomment and put in your host machines ip if 
#      want to use as a reverse proxy on linux
#    extra_hosts:
#        - "host.docker.internal:10.0.0.9"
    ports: 
      - 8080:80
      - 443:443
      - 444:443

  python:
#    image: 'python:3.6'
    build:
      context: .
      dockerfile: "docker/website/dockerfile"
    ports: 
      - 5000:5000
    environment: 
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5000
    volumes:
      - .:/app
     # for development launch directly for livereload
    #command: >
    #   sh -c "
    #    python application.py"

#    command: sleep infinity
#    command: >
#      sh -c "
#        gunicorn --bind 0.0.0.0:50603 application:app"

#    command:  >
#      sh -c "
#        cd /app  &&
#        pip install -r requirements.txt &&
#        python application.py
#        "

 # postgres:
 #   image: 'postgres'
 #   environment:
 #     POSTGRES_USER: postgres
 #     POSTGRES_PASSWORD: example
 #     POSTGRES_DB: postgres
 #     PGDATA: /var/lib/postgresql/data/pgdata
 #   ports:
 #     - 5432:5432
 #   volumes:
 #     - pgdata:/var/lib/postgresql/data/pgdata
  