version : '3'

volumes:
  pgdata:

services:

  nginx:
    depends_on:
      - python
#    image: 'python:3.6'
    build:
      context: .
      dockerfile: "docker/nginx/dockerfile"
#    extra_hosts:
#        - "hostname:10.0.0.18"
    ports: 
#      - 8080:80
      - 8080:80
      - 443:443
      - 444:444


  python:
#    image: 'python:3.6'
    build:
      context: .
      dockerfile: "docker/website/dockerfile"
    ports: 
      - 5000:5000
    environment: 
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5000
    volumes:
      - .:/app
     # for development launch directly for livereload
    command: >
       sh -c "
        python application.py"

#    command: sleep infinity
#    command: >
#      sh -c "
#        gunicorn --bind 0.0.0.0:50603 application:app"

#    command:  >
#      sh -c "
#        cd /app  &&
#        pip install -r requirements.txt &&
#        python application.py
#        "

 # postgres:
 #   image: 'postgres'
 #   environment:
 #     POSTGRES_USER: postgres
 #     POSTGRES_PASSWORD: example
 #     POSTGRES_DB: postgres
 #     PGDATA: /var/lib/postgresql/data/pgdata
 #   ports:
 #     - 5432:5432
 #   volumes:
 #     - pgdata:/var/lib/postgresql/data/pgdata
  