
FROM nginx:latest

# Setup the config
RUN rm /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/django.conf /etc/nginx/conf.d/

# Setup SSL
COPY ./website/certs/. /etc/nginx/

# Setup static files
# COPY ./website/static/. /static_files/

