
FROM nginx:latest

# Setup the config
RUN rm /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/django.proxy /etc/nginx/conf.d/
COPY ./docker/nginx/django.conf /etc/nginx/conf.d/

# Setup static files

COPY ./website/static/. /static_files/